title: "timnavigate - Software Engineer"
author: "Timur Timoshenko"
name: timnavigate
email: timnavigate@gmail.com
description: Software Engineer
url: "https://timnavigate.com"
avatar: https://raw.githubusercontent.com/timnavigate/timnavigate.github.io/master/images/timnavigate-logo.png
copyright: "(c) timnavigate, 2024"

footer-links:
  email: timnavigate@gmail.com
  github: timnavigate
  linkedin: timnavigate
  stackoverflow: "users/5113963/timnavigate"
  #youtube: "@timnavigate"
  telegram: timnavigate

permalink: /:title/

version: v1.2.0

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
