title: "timnavigate - Software Engineer"
author: "Timur Timoshenko"
name: timnavigate
email: "timnavigate@gmail.com"
description: "Software Engineer"
url: "https://timnavigate.com"
avatar: https://raw.githubusercontent.com/timnavigate/timnavigate.github.io/master/images/timnavigate-logo.png
copyright: "(c) timnavigate, 2024"

footer-links:
  email: timnavigate@gmail.com
  github: timnavigate
  linkedin: timnavigate
  stackoverflow: "users/5113963/timnavigate"
  #youtube: "@timnavigate"
  twitter: timnavigate
  telegram: timnavigate

encoding: "utf-8"
markdown: kramdown
highlighter: rouge
#theme: minima

#liquid:
#  error_mode: warn

sass:
  style: :compressed

#webrick:
#  headers:
#    My-Header: My-Value
#    My-Other-Header: My-Other-Value

#plugins:
#  - jekyll-sitemap
#  - jekyll-feed
plugins: ["jekyll-sitemap", "jekyll-feed"]

#exclude:
#  - Gemfile
#  - Gemfile.lock
include             : [".htaccess"]
exclude             : ["Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
keep_files          : [".git", ".svn"]

#port: 4000
#host: 127.0.0.1
baseurl: ""

permalink: date
#paginate_path: /page:num
#timezone: null

kramdown:
  input: GFM