title: "timnavigate - Software Engineer"
author: "Timur Timoshenko"
name: timnavigate
email: "timnavigate@gmail.com"
description: "Software Engineer"
#baseurl: ""
url: "https://timnavigate.com"
avatar: https://raw.githubusercontent.com/timnavigate/timnavigate.github.io/master/images/timnavigate-logo.png
copyright: "(c) timnavigate, 2024"

footer-links:
  email: timnavigate@gmail.com
  github: timnavigate
  linkedin: timnavigate
  stackoverflow: "users/5113963/timnavigate"
  #youtube: "@timnavigate"
  twitter: timnavigate
  telegram: timnavigate

markdown: kramdown
theme: minima

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  
